### PR TITLE
migrate from tui-rs to ratatui and add dependabot

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

Thanks for the app.
I made some minor edits.
I hope they are useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by 16arpi** [comment]
Hi! Thanks a lot for the edits :) I'll add them to the master branch.

**Review by 16arpi — CHANGES_REQUESTED** [review]
Hi! Thanks a lot for the edits :) I'll add them to the master branch. I won't add the dependabot script though... I'm not familiar to it so I won't be able to fix issues if they occur. Do you mind to remove this part ? Thanks!

**Comment by theavege** [comment]
Hi! I have removed [dependabot](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide).

**Review by 16arpi — APPROVED** [review]
Ok great thanks!

**Pull request merged**
