### PR TITLE
add github-actions

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

Thanks for your app. I add [github-actions](https://docs.github.com/en/actions) and [github-dependabot](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide). I hope they are useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by theavege** [comment]
@16arpi Could you, please, accept this PR?

**Comment by theavege** [comment]
Not answer

**Comment by 16arpi** [comment]
Hi! It's a side project, I'm very busy with my studies right now, I don't have time to dig into github actions documentation and understand the effects of your PR. Thanks for your help and patience.

**Comment by theavege** [comment]
No problem. [FYI](https://github.com/CM-IV/crypto_rs/pull/2#issuecomment-2406319038)

**Pull request closed without merging**
